version: '2'
services:
    nginx:
        image: nginx:1.15
        volumes:
            - ./dist:/usr/share/nginx:ro
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
    node:
        image: node:8
        user: root
        environment:
            - ENVIRONMENT=development
        working_dir: /home/node/app
        volumes:
            - .:/home/node/app
        command: "npm run start"