version: '3'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
  web:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./myapp:/myapp
    links:
      - db     
    depends_on:
      - db         
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web   
    depends_on:
      - web         