development:
  clients:
    default:
      database: myapp_development
      hosts:
        - db:27017
      options:
  options:
test:
  clients:
    default:
      database: myapp_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
