source 'https://rubygems.org'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.0'
  
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'  
  gem 'capybara', '>= 2.15'    
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'rails_best_practices'
  gem 'rubocop'
  gem 'rubycritic'
end

gem 'apipie-rails'
gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.0'
gem 'mongoid'
gem 'rack-attack'
gem 'rack-cors'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
